### PR TITLE
Added the Cancel Conversion call

### PR DESCRIPTION
**Pull request by eXeDK**
This adds the call the canceling a conversion.

### CODE REVIEW

**Comment by EAddario** [comment]
Thanks for the contribution eXeDK. That particular API call is still in beta and has not yet been officially released, but once this is done and the documentation is updated accordingly we will review the pull request.

**Comment by eXeDK** [comment]
Hi Ed,

We are going use this call and instead of implementing the call and logic around it ourselves it made sense to add it to the package since we are already using the package. 
We asked internally in CC if this would be fine with you guys. That is why we made this PR.

Another question, are you guys interested in typings for this package?

**Comment by EAddario** [comment]
It was the right decision Thomas and we are specially grateful to all the people that have taken time to participate in our beta releases.  I've reviewed the PR and looks solid. Assuming there are no changes on our side of the API (highly unlikely) we will close the beta and go general availability soon, at which point we will update our Development Centre site and go about the merge. For awareness, there may be one or two small changes we will request but let's cross that bridge when we get there.

As for the typings offer, Yes!!! but please hold back for a couple weeks before submitting. We're putting together a contributors.md file to help ease the process.

**Comment by eXeDK** [comment]
Fair enough. We'll put on our waiting hat for a bit.

I'll write the last of the typings and create a new PR for that later on.

**Pull request merged**
